apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connect-example-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # 来源：指向您的 Helm Chart 仓库（即应用代码仓库）
  source:
    # 指向包含 Helm Chart 的 Git 仓库 URL或OCI 仓库 URL
    #    repoURL: https://github.com/sunmery/connect-example.git
    repoURL: oci://harbor.apikv.com:5443/sumery
    chart: connect-example-frontend-chart # 这是你打包的 Chart 的名称
    # 指定 Chart 版本
    targetRevision: 1.0.0

    helm:
      valueFiles:
        - values.yaml
  # 目标：指定部署到哪个集群和命名空间
  destination:
    server: "https://kubernetes.default.svc" # 集群 API Server 地址
    namespace: connect-example

  # 同步策略
  syncPolicy:
    automated: # 启用自动化同步
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 自动创建命名空间
