apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connect-example-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/oci/
    repoURL: oci://harbor.apikv.com:5443/sumery/backend
    # repoURL: oci://ghcr.io/sunmery/connect-example/backend
    # 指定 Chart 版本
    targetRevision: 1.5.1
    path: .
    helm:
      valueFiles:
        - values.yaml
      passCredentials: true
  # 目标：指定部署到哪个集群和命名空间
  destination:
    # 集群 API Server 地址
    server: https://kubernetes.default.svc
    # 要部署到的命名空间
    namespace: connect-example
  # 同步策略
  syncPolicy:
    automated: # 启用自动化同步
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 自动创建命名空间
